apiVersion: v1
kind: Service
metadata:
  name: students-management-service
spec:
  selector:
    app: students-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
