apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-management-deployment
  labels:
    app: students-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-management
  template:
    metadata:
      labels:
        app: students-management
    spec:
      containers:
        - name: students-management
          image: mayss111/students-management:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: students-management-service
spec:
  selector:
    app: students-management
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007  # port accessible via Minikube IP

