apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-management-deployment
  labels:
    app: students-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-management
  template:
    metadata:
      labels:
        app: students-management
    spec:
      containers:
        - name: students-management
          image: students-management:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: students-management-service
spec:
  selector:
    app: students-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
